### ISSUE TITLE
Not compatible with Android L (5.0.1)

### ISSUE THREAD

**Issue by brownemint** [appcelerator-modules/ti.urbanairship#6]
Getting the following error on a device (Nexus 4) at startup. Checked on devices not running L and no issues. Ti SDK - 3.5.0.GA

```
D/UrbanAirshipModule( 7628): (main) [24,276] Received onAppCreate notification
I/UrbanAirshipModule( 7628): (main) [0,276] Airship taking off
D/Version 2 - UALib( 7628): Airship Take Off! Lib Version: 2.0.3 / App key = nZ0p4b22Q2KhQP-3UlOVgg
D/Version 2 - UALib( 7628): In Production? false
D/Version 2 - UALib( 7628): Initializing Push.
D/Version 2 - UALib( 7628): Initializing Analytics.
W/V8Object( 7628): (KrollRuntimeThread) [256,532] Runtime disposed, cannot set property 'userAgent'
D/Version 2 APID( 7628): 8cbfe79c-d1a6-4625-be18-cdcfec9491cd
D/Version 2 - UALib( 7628): Package (com.ista.version2) was replaced. Resetting GCM ID.
D/Version 2 - UALib( 7628): Push Service started with intent=Intent { act=com.urbanairship.push.START cmp=com.ista.version2/com.urbanairship.push.PushService }
D/Version 2 - UALib( 7628): Push enabled: true
D/Version 2 - UALib( 7628): Starting GCM
I/Version 2 - UALib( 7628): Initializing GCM Push...
I/ActivityManager(  555): Start proc com.google.android.calendar for broadcast com.google.android.calendar/com.android.calendar.widget.WidgetDataReceiver: pid=7659 uid=10006 gids={50006, 9997, 3003, 1028, 1015} abi=armeabi-v7a
E/SQLiteLog( 7659): (283) recovered 94 frames from WAL file /data/data/com.google.android.calendar/databases/timelydata.db-wal
I/art     (  555): Explicit concurrent mark sweep GC freed 17410(743KB) AllocSpace objects, 1(16KB) LOS objects, 33% free, 31MB/46MB, paused 1.892ms total 150.740ms
E/AndroidRuntime( 7628): FATAL EXCEPTION: IntentService[PushWorkerService]
E/AndroidRuntime( 7628): Process: com.ista.version2, PID: 7628
E/AndroidRuntime( 7628): java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.google.android.c2dm.intent.REGISTER (has extras) }
E/AndroidRuntime( 7628): 	at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1674)
E/AndroidRuntime( 7628): 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1703)
E/AndroidRuntime( 7628): 	at android.app.ContextImpl.startService(ContextImpl.java:1687)
E/AndroidRuntime( 7628): 	at android.content.ContextWrapper.startService(ContextWrapper.java:515)
E/AndroidRuntime( 7628): 	at com.urbanairship.push.GCMPushManager.register(Unknown Source)
E/AndroidRuntime( 7628): 	at com.urbanairship.push.PushWorkerService.onHandleIntent(Unknown Source)
E/AndroidRuntime( 7628): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/AndroidRuntime( 7628): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 7628): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 7628): 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by jsplaine** [comment]
We're stuck using an old Titanium SDK because of this issue.  We're running Ti SDK 3.5.1.GA and phones running 5.0.1+ crash on launch and cannot receive push notifications.

Any plans for a fix?

```
[ERROR] :  TiApplication: (IntentService[PushWorkerService]) [1788,1992] Sending event: exception on thread: IntentService[PushWorkerService] msg:java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.google.android.c2dm.intent.REGISTER (has extras) }; Titanium 3.5.1,2015/03/05 10:08,96875c9
[ERROR] :  TiApplication: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.google.android.c2dm.intent.REGISTER (has extras) }
[ERROR] :  TiApplication: 	at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:2117)
[ERROR] :  TiApplication: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:2155)
[ERROR] :  TiApplication: 	at android.app.ContextImpl.startService(ContextImpl.java:2130)
[ERROR] :  TiApplication: 	at android.content.ContextWrapper.startService(ContextWrapper.java:534)
[ERROR] :  TiApplication: 	at com.urbanairship.push.GCMPushManager.register(Unknown Source)
[ERROR] :  TiApplication: 	at com.urbanairship.push.PushWorkerService.onHandleIntent(Unknown Source)
[ERROR] :  TiApplication: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:145)
[ERROR] :  TiApplication: 	at android.os.HandlerThread.run(HandlerThread.java:61)
[ERROR] :  AndroidRuntime: FATAL EXCEPTION: IntentService[PushWorkerService]
[ERROR] :  AndroidRuntime: Process: com.onforce.OnForce, PID: 6206
[ERROR] :  AndroidRuntime: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.google.android.c2dm.intent.REGISTER (has extras) }
[ERROR] :  AndroidRuntime: 	at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:2117)
[ERROR] :  AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:2155)
[ERROR] :  AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:2130)
[ERROR] :  AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:534)
[ERROR] :  AndroidRuntime: 	at com.urbanairship.push.GCMPushManager.register(Unknown Source)
[ERROR] :  AndroidRuntime: 	at com.urbanairship.push.PushWorkerService.onHandleIntent(Unknown Source)
[ERROR] :  AndroidRuntime: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
[ERROR] :  AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  AndroidRuntime: 	at android.os.Looper.loop(Looper.java:145)
[ERROR] :  AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
[WARN] :   TiLaunchActivity: (main) [344,2336] Tasks may have been destroyed by Android OS for inactivity. Restarting.
```

**Comment by brownemint** [comment]
I logged a [ticket](https://jira.appcelerator.org/browse/TIMOB-18498) with Appcelerator because the problem was due to the android-support-v4.jar being out of date in version 3.5.0.GA

It should be fixed in the 4.0.0 release.

If you are intent on using 3.5.1.GA then you'll need to fork the version of the SDK yourself and update the jar file. That worked for me as a temporary solution until the official patch from Appcelerator.

**Comment by chmiiller** [comment]
Hey folks, any news on that?
I'm using Ti SDK 5.1.2GA and my Android 5+ phones are not registering for notifications =/

**Comment by ChanakyaSrinivas** [comment]
Hi All,

I'm also facing same problem.
I'm using Ti SDK 5.1.2GA.
```
[ERROR] :  TiApplication: (IntentService[PushWorkerService]) [7149,13327] Sending event: exception on thread: IntentService[PushWorkerService] msg:java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.google.android.c2dm.intent.REGISTER (has extras) }; Titanium 5.2.1,2016/03/18 22:51,23e1c7d
[ERROR] :  TiApplication: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.google.android.c2dm.intent.REGISTER (has extras) }
[ERROR] :  TiApplication: 	at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1819)
[ERROR] :  TiApplication: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1848)
[ERROR] :  TiApplication: 	at android.app.ContextImpl.startService(ContextImpl.java:1832)
[ERROR] :  TiApplication: 	at android.content.ContextWrapper.startService(ContextWrapper.java:516)
[ERROR] :  TiApplication: 	at com.urbanairship.push.GCMPushManager.register(Unknown Source)
[ERROR] :  TiApplication: 	at com.urbanairship.push.PushWorkerService.onHandleIntent(Unknown Source)
[ERROR] :  TiApplication: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:135)
```

Can any help me, How to resolve it.

**Comment by chmiiller** [comment]
Have a look at this:
http://stackoverflow.com/questions/36206479/push-notifications-on-android-5-not-delivered-when-app-in-background-titanium

I'm trying to update @rdking module but still not working with the app on background =/

**Comment by ChanakyaSrinivas** [comment]
I heard that Urban Airship is not supporting Titanium.
I am confusion whether ti.urbanairship module is working for titanium android app to send notifications.
If ti.urbanairship module is working for titanium android app, which version of module I have to use for Ti SDK 5.2.1GA

**Comment by negatr0n** [comment]
@brownemint Have you found a workaround?  The 4.0 patch did not seem to help...

**Comment by brownemint** [comment]
I've since moved away from using UrbanAirship in favour of sending pushes from my own server. Sorry I can't be of more help.

From what I've read in this [issue](https://github.com/appcelerator-modules/ti.urbanairship/issues/7), it seems Appcelerator are no longer maintaining ti.urbanairship

**Comment by TinyGiantDigital** [comment]
FYI Urban Airship have now started to develop a Titanium module. See here: http://docs.urbanairship.com/platform/titanium.html and the module can be downloaded here: https://bintray.com/urbanairship/titanium/titanium-module/view#
